//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import followIfLoginRedirect from './components/api-authorization/followIfLoginRedirect';

export class AccountClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    account_Me(): Promise<MeResponse> {
        let url_ = this.baseUrl + "/api/Account/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAccount_Me(_response);
        });
    }

    protected processAccount_Me(response: Response): Promise<MeResponse> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MeResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MeResponse>(null as any);
    }
}

export class AdminTicketsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    adminTickets_GetTickets(): Promise<AdminTicketDto[]> {
        let url_ = this.baseUrl + "/api/admin/tickets";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAdminTickets_GetTickets(_response);
        });
    }

    protected processAdminTickets_GetTickets(response: Response): Promise<AdminTicketDto[]> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(AdminTicketDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AdminTicketDto[]>(null as any);
    }

    adminTickets_AcceptTicket(id: number): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/admin/tickets/{id}/accept";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAdminTickets_AcceptTicket(_response);
        });
    }

    protected processAdminTickets_AcceptTicket(response: Response): Promise<FileResponse> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    adminTickets_UpdateTicket(id: number, request: UpdateTicketRequest): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/admin/tickets/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAdminTickets_UpdateTicket(_response);
        });
    }

    protected processAdminTickets_UpdateTicket(response: Response): Promise<FileResponse> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    adminTickets_DeleteTicket(id: number): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/admin/tickets/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAdminTickets_DeleteTicket(_response);
        });
    }

    protected processAdminTickets_DeleteTicket(response: Response): Promise<FileResponse> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class ReportsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    reports_GetTicketsSummary(): Promise<TicketSummaryDto[]> {
        let url_ = this.baseUrl + "/api/Reports/tickets-summary";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReports_GetTicketsSummary(_response);
        });
    }

    protected processReports_GetTicketsSummary(response: Response): Promise<TicketSummaryDto[]> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TicketSummaryDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TicketSummaryDto[]>(null as any);
    }
}

export class TicketCategoriesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    ticketCategories_GetCategories(): Promise<TicketCategory[]> {
        let url_ = this.baseUrl + "/api/TicketCategories";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTicketCategories_GetCategories(_response);
        });
    }

    protected processTicketCategories_GetCategories(response: Response): Promise<TicketCategory[]> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TicketCategory.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TicketCategory[]>(null as any);
    }
}

export class TicketsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    tickets_GetTickets(): Promise<TicketDto[]> {
        let url_ = this.baseUrl + "/api/Tickets";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTickets_GetTickets(_response);
        });
    }

    protected processTickets_GetTickets(response: Response): Promise<TicketDto[]> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TicketDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TicketDto[]>(null as any);
    }

    tickets_CreateTicket(request: CreateTicketRequest): Promise<number> {
        let url_ = this.baseUrl + "/api/Tickets";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTickets_CreateTicket(_response);
        });
    }

    protected processTickets_CreateTicket(response: Response): Promise<number> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    tickets_GetTicket(id: number): Promise<TicketDetailsDto> {
        let url_ = this.baseUrl + "/api/Tickets/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTickets_GetTicket(_response);
        });
    }

    protected processTickets_GetTicket(response: Response): Promise<TicketDetailsDto> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TicketDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TicketDetailsDto>(null as any);
    }

    tickets_GetCategories(): Promise<CategoryDto[]> {
        let url_ = this.baseUrl + "/api/Tickets/categories";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTickets_GetCategories(_response);
        });
    }

    protected processTickets_GetCategories(response: Response): Promise<CategoryDto[]> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(CategoryDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CategoryDto[]>(null as any);
    }
}

export class MeResponse implements IMeResponse {
    isAuthenticated?: boolean;
    userName?: string | undefined;
    email?: string | undefined;
    roles?: string[];
    createdTicketsCount?: number;
    openTicketsCount?: number;
    resolvedTicketsCount?: number;
    assignedTicketsCount?: number;

    constructor(data?: IMeResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isAuthenticated = _data["isAuthenticated"];
            this.userName = _data["userName"];
            this.email = _data["email"];
            if (Array.isArray(_data["roles"])) {
                this.roles = [] as any;
                for (let item of _data["roles"])
                    this.roles!.push(item);
            }
            this.createdTicketsCount = _data["createdTicketsCount"];
            this.openTicketsCount = _data["openTicketsCount"];
            this.resolvedTicketsCount = _data["resolvedTicketsCount"];
            this.assignedTicketsCount = _data["assignedTicketsCount"];
        }
    }

    static fromJS(data: any): MeResponse {
        data = typeof data === 'object' ? data : {};
        let result = new MeResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isAuthenticated"] = this.isAuthenticated;
        data["userName"] = this.userName;
        data["email"] = this.email;
        if (Array.isArray(this.roles)) {
            data["roles"] = [];
            for (let item of this.roles)
                data["roles"].push(item);
        }
        data["createdTicketsCount"] = this.createdTicketsCount;
        data["openTicketsCount"] = this.openTicketsCount;
        data["resolvedTicketsCount"] = this.resolvedTicketsCount;
        data["assignedTicketsCount"] = this.assignedTicketsCount;
        return data;
    }
}

export interface IMeResponse {
    isAuthenticated?: boolean;
    userName?: string | undefined;
    email?: string | undefined;
    roles?: string[];
    createdTicketsCount?: number;
    openTicketsCount?: number;
    resolvedTicketsCount?: number;
    assignedTicketsCount?: number;
}

export class AdminTicketDto implements IAdminTicketDto {
    id?: number;
    title?: string;
    categoryName?: string | undefined;
    priority?: number;
    status?: string;
    adminComment?: string | undefined;
    createdBy?: string;
    createdAt?: Date;
    assignedToUserId?: string | undefined;
    isAccepted?: boolean;

    constructor(data?: IAdminTicketDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.categoryName = _data["categoryName"];
            this.priority = _data["priority"];
            this.status = _data["status"];
            this.adminComment = _data["adminComment"];
            this.createdBy = _data["createdBy"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.assignedToUserId = _data["assignedToUserId"];
            this.isAccepted = _data["isAccepted"];
        }
    }

    static fromJS(data: any): AdminTicketDto {
        data = typeof data === 'object' ? data : {};
        let result = new AdminTicketDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["categoryName"] = this.categoryName;
        data["priority"] = this.priority;
        data["status"] = this.status;
        data["adminComment"] = this.adminComment;
        data["createdBy"] = this.createdBy;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["assignedToUserId"] = this.assignedToUserId;
        data["isAccepted"] = this.isAccepted;
        return data;
    }
}

export interface IAdminTicketDto {
    id?: number;
    title?: string;
    categoryName?: string | undefined;
    priority?: number;
    status?: string;
    adminComment?: string | undefined;
    createdBy?: string;
    createdAt?: Date;
    assignedToUserId?: string | undefined;
    isAccepted?: boolean;
}

export class UpdateTicketRequest implements IUpdateTicketRequest {
    status?: string;
    adminComment?: string | undefined;

    constructor(data?: IUpdateTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.status = _data["status"];
            this.adminComment = _data["adminComment"];
        }
    }

    static fromJS(data: any): UpdateTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["status"] = this.status;
        data["adminComment"] = this.adminComment;
        return data;
    }
}

export interface IUpdateTicketRequest {
    status?: string;
    adminComment?: string | undefined;
}

export class TicketSummaryDto implements ITicketSummaryDto {
    categoryId?: number;
    categoryName?: string;
    totalTickets?: number;
    newTickets?: number;
    inProgressTickets?: number;
    resolvedTickets?: number;
    rejectedTickets?: number;

    constructor(data?: ITicketSummaryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.categoryId = _data["categoryId"];
            this.categoryName = _data["categoryName"];
            this.totalTickets = _data["totalTickets"];
            this.newTickets = _data["newTickets"];
            this.inProgressTickets = _data["inProgressTickets"];
            this.resolvedTickets = _data["resolvedTickets"];
            this.rejectedTickets = _data["rejectedTickets"];
        }
    }

    static fromJS(data: any): TicketSummaryDto {
        data = typeof data === 'object' ? data : {};
        let result = new TicketSummaryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["categoryId"] = this.categoryId;
        data["categoryName"] = this.categoryName;
        data["totalTickets"] = this.totalTickets;
        data["newTickets"] = this.newTickets;
        data["inProgressTickets"] = this.inProgressTickets;
        data["resolvedTickets"] = this.resolvedTickets;
        data["rejectedTickets"] = this.rejectedTickets;
        return data;
    }
}

export interface ITicketSummaryDto {
    categoryId?: number;
    categoryName?: string;
    totalTickets?: number;
    newTickets?: number;
    inProgressTickets?: number;
    resolvedTickets?: number;
    rejectedTickets?: number;
}

export class TicketCategory implements ITicketCategory {
    id?: number;
    name?: string;
    description?: string | undefined;
    tickets?: Ticket[];

    constructor(data?: ITicketCategory) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            if (Array.isArray(_data["tickets"])) {
                this.tickets = [] as any;
                for (let item of _data["tickets"])
                    this.tickets!.push(Ticket.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TicketCategory {
        data = typeof data === 'object' ? data : {};
        let result = new TicketCategory();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        if (Array.isArray(this.tickets)) {
            data["tickets"] = [];
            for (let item of this.tickets)
                data["tickets"].push(item.toJSON());
        }
        return data;
    }
}

export interface ITicketCategory {
    id?: number;
    name?: string;
    description?: string | undefined;
    tickets?: Ticket[];
}

export class Ticket implements ITicket {
    id?: number;
    title?: string;
    description?: string;
    priority?: number;
    status?: string;
    categoryId?: number;
    category?: TicketCategory | undefined;
    createdByUserId?: string;
    assignedToUserId?: string | undefined;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    adminComment?: string | undefined;
    statusHistory?: TicketStatusHistory[];

    constructor(data?: ITicket) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.priority = _data["priority"];
            this.status = _data["status"];
            this.categoryId = _data["categoryId"];
            this.category = _data["category"] ? TicketCategory.fromJS(_data["category"]) : <any>undefined;
            this.createdByUserId = _data["createdByUserId"];
            this.assignedToUserId = _data["assignedToUserId"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : <any>undefined;
            this.adminComment = _data["adminComment"];
            if (Array.isArray(_data["statusHistory"])) {
                this.statusHistory = [] as any;
                for (let item of _data["statusHistory"])
                    this.statusHistory!.push(TicketStatusHistory.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Ticket {
        data = typeof data === 'object' ? data : {};
        let result = new Ticket();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["priority"] = this.priority;
        data["status"] = this.status;
        data["categoryId"] = this.categoryId;
        data["category"] = this.category ? this.category.toJSON() : <any>undefined;
        data["createdByUserId"] = this.createdByUserId;
        data["assignedToUserId"] = this.assignedToUserId;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : <any>undefined;
        data["adminComment"] = this.adminComment;
        if (Array.isArray(this.statusHistory)) {
            data["statusHistory"] = [];
            for (let item of this.statusHistory)
                data["statusHistory"].push(item.toJSON());
        }
        return data;
    }
}

export interface ITicket {
    id?: number;
    title?: string;
    description?: string;
    priority?: number;
    status?: string;
    categoryId?: number;
    category?: TicketCategory | undefined;
    createdByUserId?: string;
    assignedToUserId?: string | undefined;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    adminComment?: string | undefined;
    statusHistory?: TicketStatusHistory[];
}

export class TicketStatusHistory implements ITicketStatusHistory {
    id?: number;
    ticketId?: number;
    ticket?: Ticket | undefined;
    oldStatus?: string | undefined;
    newStatus?: string;
    changedByUserId?: string;
    changedAt?: Date;
    comment?: string | undefined;

    constructor(data?: ITicketStatusHistory) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.ticketId = _data["ticketId"];
            this.ticket = _data["ticket"] ? Ticket.fromJS(_data["ticket"]) : <any>undefined;
            this.oldStatus = _data["oldStatus"];
            this.newStatus = _data["newStatus"];
            this.changedByUserId = _data["changedByUserId"];
            this.changedAt = _data["changedAt"] ? new Date(_data["changedAt"].toString()) : <any>undefined;
            this.comment = _data["comment"];
        }
    }

    static fromJS(data: any): TicketStatusHistory {
        data = typeof data === 'object' ? data : {};
        let result = new TicketStatusHistory();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["ticketId"] = this.ticketId;
        data["ticket"] = this.ticket ? this.ticket.toJSON() : <any>undefined;
        data["oldStatus"] = this.oldStatus;
        data["newStatus"] = this.newStatus;
        data["changedByUserId"] = this.changedByUserId;
        data["changedAt"] = this.changedAt ? this.changedAt.toISOString() : <any>undefined;
        data["comment"] = this.comment;
        return data;
    }
}

export interface ITicketStatusHistory {
    id?: number;
    ticketId?: number;
    ticket?: Ticket | undefined;
    oldStatus?: string | undefined;
    newStatus?: string;
    changedByUserId?: string;
    changedAt?: Date;
    comment?: string | undefined;
}

export class TicketDto implements ITicketDto {
    id?: number;
    title?: string;
    description?: string;
    priority?: number;
    status?: string;
    categoryName?: string | undefined;
    createdAt?: Date;
    adminComment?: string | undefined;

    constructor(data?: ITicketDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.priority = _data["priority"];
            this.status = _data["status"];
            this.categoryName = _data["categoryName"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.adminComment = _data["adminComment"];
        }
    }

    static fromJS(data: any): TicketDto {
        data = typeof data === 'object' ? data : {};
        let result = new TicketDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["priority"] = this.priority;
        data["status"] = this.status;
        data["categoryName"] = this.categoryName;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["adminComment"] = this.adminComment;
        return data;
    }
}

export interface ITicketDto {
    id?: number;
    title?: string;
    description?: string;
    priority?: number;
    status?: string;
    categoryName?: string | undefined;
    createdAt?: Date;
    adminComment?: string | undefined;
}

export class TicketDetailsDto implements ITicketDetailsDto {
    id?: number;
    title?: string;
    description?: string;
    priority?: number;
    status?: string;
    categoryName?: string | undefined;
    createdAt?: Date;
    createdBy?: string;
    adminComment?: string | undefined;
    history?: StatusHistoryItemDto[];

    constructor(data?: ITicketDetailsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.priority = _data["priority"];
            this.status = _data["status"];
            this.categoryName = _data["categoryName"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.createdBy = _data["createdBy"];
            this.adminComment = _data["adminComment"];
            if (Array.isArray(_data["history"])) {
                this.history = [] as any;
                for (let item of _data["history"])
                    this.history!.push(StatusHistoryItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TicketDetailsDto {
        data = typeof data === 'object' ? data : {};
        let result = new TicketDetailsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["priority"] = this.priority;
        data["status"] = this.status;
        data["categoryName"] = this.categoryName;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["createdBy"] = this.createdBy;
        data["adminComment"] = this.adminComment;
        if (Array.isArray(this.history)) {
            data["history"] = [];
            for (let item of this.history)
                data["history"].push(item.toJSON());
        }
        return data;
    }
}

export interface ITicketDetailsDto {
    id?: number;
    title?: string;
    description?: string;
    priority?: number;
    status?: string;
    categoryName?: string | undefined;
    createdAt?: Date;
    createdBy?: string;
    adminComment?: string | undefined;
    history?: StatusHistoryItemDto[];
}

export class StatusHistoryItemDto implements IStatusHistoryItemDto {
    oldStatus?: string | undefined;
    newStatus?: string;
    changedAt?: Date;
    changedBy?: string;
    comment?: string | undefined;

    constructor(data?: IStatusHistoryItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.oldStatus = _data["oldStatus"];
            this.newStatus = _data["newStatus"];
            this.changedAt = _data["changedAt"] ? new Date(_data["changedAt"].toString()) : <any>undefined;
            this.changedBy = _data["changedBy"];
            this.comment = _data["comment"];
        }
    }

    static fromJS(data: any): StatusHistoryItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new StatusHistoryItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["oldStatus"] = this.oldStatus;
        data["newStatus"] = this.newStatus;
        data["changedAt"] = this.changedAt ? this.changedAt.toISOString() : <any>undefined;
        data["changedBy"] = this.changedBy;
        data["comment"] = this.comment;
        return data;
    }
}

export interface IStatusHistoryItemDto {
    oldStatus?: string | undefined;
    newStatus?: string;
    changedAt?: Date;
    changedBy?: string;
    comment?: string | undefined;
}

export class CategoryDto implements ICategoryDto {
    id?: number;
    name?: string;

    constructor(data?: ICategoryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CategoryDto {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface ICategoryDto {
    id?: number;
    name?: string;
}

export class CreateTicketRequest implements ICreateTicketRequest {
    title?: string;
    description?: string;
    priority?: number;
    categoryId?: number;

    constructor(data?: ICreateTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.description = _data["description"];
            this.priority = _data["priority"];
            this.categoryId = _data["categoryId"];
        }
    }

    static fromJS(data: any): CreateTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["description"] = this.description;
        data["priority"] = this.priority;
        data["categoryId"] = this.categoryId;
        return data;
    }
}

export interface ICreateTicketRequest {
    title?: string;
    description?: string;
    priority?: number;
    categoryId?: number;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}